### ISSUE TITLE
Feature: User can create new entry

### ISSUE THREAD

**Issue by tevnicolas** [tevnicolas/front-end-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create new coordinates entry and
receive data back and a summary about their future climate

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Typing in coordinates. Click submit.

## 🖼️ Wireframes
![Screenshot 2024-03-05 at 11 25 03 AM](https://github.com/tevnicolas/front-end-project/assets/155599138/58212b75-00db-485b-95a7-13b672a6344d)

![Screenshot 2024-03-05 at 11 26 17 AM](https://github.com/tevnicolas/front-end-project/assets/155599138/a46e4bd0-9db3-498b-8d84-cee8ea6cb063)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the header
- [x] Create the html for the landing page
- [x] Create HTML for the form page
- [x] Write CSS, for mobile first
    - [x] Adjust Styling to fluidly adapt to desktop
- [x] Add a 'submit' event listener to the landing page element that:
     - [x] prevents the page from refreshing when the form is submitted.
     - [x] Makes a call to the API with the form values and awaits a response
     - [x] stores the form's API response and form values in a new object.
     - [x] assigns an entryId property to the new object, taken from the nextEntryId property of the data model.
     - [x] view swap to New Entry Page and render Object with the new object
     - [x] increments the nextEntryId property of the data model so that if another entry is submitted later, it will receive a different entryId.
     - [x] adds the new object to the beginning of the data model's array of entries.
     - [x] resets the preview image's src attribute back to the placeholder image.
     - [x] resets the form.
- [x]  At the bottom of data.js, include a conditional statement that:
     - [x] checks to see if there is a JSON data model stored in localStorage.
     - [x] if there is, parse it and assign it to the initial data variable so that the user can continue adding entries to the pre-existing data model.
- [x] Test the app by submitting some new entries and then reloading the page to confirm that:
     - [x] the data model is being saved to localStorage before each page reload.
     - [x] each new journal entry object is receiving an incrementing entryId property.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
